module.exports = [
  { symbol: "TCS", name: "Tata Consultancy Services", sector: "IT" },
  { symbol: "INFY", name: "Infosys", sector: "IT" },
  { symbol: "RELIANCE", name: "Reliance Industries", sector: "Energy" },
  { symbol: "HDFC", name: "HDFC Bank", sector: "Banking" },
  { symbol: "ICICI", name: "ICICI Bank", sector: "Banking" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecom" },
  { symbol: "HCLTECH", name: "HCL Technologies", sector: "IT" },
  { symbol: "ITC", name: "ITC Limited", sector: "FMCG" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Banking" },
  { symbol: "LT", name: "Larsen & Toubro", sector: "Infra" },
  { symbol: "AXISBANK", name: "Axis Bank", sector: "Banking" },
  { symbol: "WIPRO", name: "Wipro", sector: "IT" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", sector: "Finance" },
  { symbol: "MARUTI", name: "Maruti Suzuki", sector: "Auto" },
  { symbol: "TITAN", name: "Titan Company", sector: "Consumer" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", sector: "Pharma" },
  { symbol: "TATAMOTORS", name: "Tata Motors", sector: "Auto" },
  { symbol: "ASIANPAINT", name: "Asian Paints", sector: "Consumer" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", sector: "Cement" }
];
